#' @title 95\%-confidence intervals for LoA (3 methods)
#'
#' @description \code{blandxtr_ci} returns 95\%-confidence intervals (95\%-CI)
#' for limits of agreement (LoA) based on three different methods
#' (Bland and Altman (1999), MOVER and parametric bootstrap-t)
#'
#' @author Inga Koenemund \email{inga.koenemund@web.de}
#'
#' @param bt number of bootstrap samples
#' @param input_dt data.table with input dataset
#' @param biasMod set TRUE for modified calculation of bias (small wsv),
#' set FALSE for standard calculation of bias (small bsv)
#' @param bv result of \code{basicVariables.R}
#' @param var_tvv result of \code{var_tvv.R}
#' @param loa result of \code{loa.R}
#' @param loa_mod result of \code{loa.R} based on modified tvv
#' @param var_loa result of \code{var.loa.R}
#' @param var_loa_mod result of \code{var.loa.R} based on modified tvv
#'
#' @note Input can easily generated by previously running
#' \code{blandxtrMain.pre}
#' @seealso [blandxtrMain_pre()]
#'
#' @return A list with confidence intervals of the three methods


blandxtr_ci <- function(bt, input_dt, biasMod, bv, var_tvv, loa, loa_mod,
  var_loa, var_loa_mod){
  # -----------------------------------------
  # CI Bland Altman
  source("R/ci.loa.ba.R")
  # CI Bland Altman (based on standard tvv)
  loa_ba <- calc_ci_loa_ba (loa$loa_l, loa$loa_u, var_loa)

  # CI Bland Altman (based on modified tvv)
  # mod: uses modified versions of loa (modified tvv)
  loa_ba_mod <- calc_ci_loa_ba (loa_mod$loa_l, loa_mod$loa_u, var_loa_mod)

  # -----------------------------------------
  # CI mover
  # mod: uses modified versions of loa (modified tvv)
  source("R/ci.loa.mover.R")

  # CI mover (based on standard tvv)
  loa_mover <- calc_ci_loa_mover (bv$n, bv$n_obs, bv$outputSubjects,
    var_tvv$bsv_mod, var_tvv$wsv, loa$loa_l, loa$loa_u)

  # CI mover (based on modified tvv)
  loa_mover_mod <- calc_ci_loa_mover (bv$n, bv$n_obs, bv$outputSubjects,
    var_tvv$bsv_mod, var_tvv$wsv_mod, loa_mod$loa_l, loa_mod$loa_u)

  # -----------------------------------------
  # CI bootstrap: only executed if bt > 0
  # mod: uses modified versions of loa (modified tvv)
  if (bt > 0){
    source("R/ci.loa.bt.R")

    # CI bootstrap (based on standard tvv)
    loa_bt <- calc_ci_loa_bt (bt, input_dt, biasMod, loa$loa_l, loa$loa_u, var_loa)

    # CI bootstrap (based on modified tvv)
    loa_bt_mod <- calc_ci_loa_bt (bt, input_dt, biasMod, loa_mod$loa_l,
      loa_mod$loa_u, var_loa_mod)

  }
  # -----------------------------------------

  return(
    if (bt > 0){
      list(
        loa_ba = loa_ba,
        loa_ba_mod = loa_ba_mod,
        loa_mover = loa_mover,
        loa_mover_mod = loa_mover_mod,
        loa_bt = loa_bt,
        loa_bt_mod = loa_bt_mod
      )
    } else {
      list(
        loa_ba = loa_ba,
        loa_ba_mod = loa_ba_mod,
        loa_mover = loa_mover,
        loa_mover_mod = loa_mover_mod
      )
    }
  )
}
