#' @title Calculatin of confidence intervals for limits of agreement (3 methods)
#'
#' @description \code{main_ci} returns confidence intervals (CI)
#' for limits of agreement (LoA) based on three different methods
#' (Bland and Altman (1999), MOVER and parametric bootstrap-t). Helper function
#' for \code{blandxtr} which performs the whole analysis.
#'
#' @author Inga Koenemund \email{inga.koenemund@@web.de}
#'
#' @param bt number of bootstrap samples
#' @param input_dt data.table with input dataset
#' @param bias_alt set TRUE for alternative calculation of bias (small
#' within-subject variance) and its variance, set FALSE for standard calculation
#' of bias (small between-subjects variance) and its variance
#' @param bv result of \code{basic_variables.R}
#' @param var_tvv result of \code{var_tvv.R}
#' @param loa result of \code{loa.R}
#' @param loa_mod result of \code{loa.R} based on modified analysis of variance
#' @param var_loa result of \code{var_loa.R}
#' @param var_loa_mod result of \code{var_loa.R} based on modified analysis
#' of variance
#' @param alpha for 100*(1-alpha)\%-confidence interval around LoA
#' @param beta for 100*(1-beta)\%-confidence interval around bias
#'
#' @note Input can  be easily generated by previously running
#' \code{main-pre}-function from \code{blandxtr}-package.
#'
#' @return A list with confidence intervals of the three methods
#' @export


main_ci <- function(bt, input_dt, bias_alt, bv, var_tvv, loa, loa_mod,
  var_loa, var_loa_mod, alpha, beta){

  # -----------------------------------------
  # check input
  coll <- checkmate::makeAssertCollection()
  checkmate::assert_int(bt, add = coll)
  checkmate::assert_data_table(input_dt, add = coll)
  checkmate::assert_logical(bias_alt, add = coll)
  checkmate::assert_list(bv, add = coll)
  checkmate::assert_list(var_tvv, add = coll)
  checkmate::assert_list(loa, add = coll)
  checkmate::assert_list(loa_mod, add = coll)
  checkmate::assert_numeric(var_loa, add = coll)
  checkmate::assert_numeric(var_loa_mod, add = coll)
  checkmate::assert_numeric(alpha, lower = 0, upper = 1, add = coll)
  checkmate::assert_numeric(beta, lower = 0, upper = 1, add = coll)
  checkmate::reportAssertions(coll)
  # -----------------------------------------

  # -----------------------------------------
  # calculation of confidence intervals (method by Bland and Altman)

  # CI Bland Altman (based on standard analysis of variance)
  ci_loa_ba <- ci_loa_ba (loa$loa_l, loa$loa_u, var_loa, alpha)

  # CI Bland Altman (based on modified analysis of variance)
  ci_loa_ba_mod <- ci_loa_ba (loa_mod$loa_l, loa_mod$loa_u, var_loa_mod,
    alpha)

  # -----------------------------------------
  # calculation of confidence intervals (MOVER method)

  # CI MOVER (based on standard analysis of variance)
  ci_loa_mover <- ci_loa_mover (bv$n, bv$n_obs, bv$output_subjects,
    var_tvv$mssi_mod, var_tvv$wsv, loa$loa_l, loa$loa_u, alpha, beta)

  # CI MOVER (based on modified analysis of variance)
  ci_loa_mover_mod <- ci_loa_mover (bv$n, bv$n_obs, bv$output_subjects,
    var_tvv$mssi_mod, var_tvv$wsv_mod, loa_mod$loa_l, loa_mod$loa_u, alpha,
    beta)

  # -----------------------------------------
  # calculation of confidence intervals (using parametric bootstrap-t)
  # bootstrapping is skipped if bt <= 0

  if (bt > 0){
    # CI bootstrap (based on standard analysis of variance)
    ci_loa_bt <- ci_loa_bt (bt, input_dt, bias_alt, loa$loa_l,
      loa$loa_u, var_loa, alpha, beta, bv$n, bv$n_obs, bv$d, bv$d_a,
      var_tvv$bsv, var_tvv$wsv)

    # CI bootstrap (based on modified analysis of variance)
    ci_loa_bt_mod <- ci_loa_bt (bt, input_dt, bias_alt, loa_mod$loa_l,
      loa_mod$loa_u, var_loa_mod, alpha, beta, bv$n, bv$n_obs, bv$d, bv$d_a,
      var_tvv$bsv_mod, var_tvv$wsv_mod)
  }

  # -----------------------------------------
  return(
    if (bt > 0){
      list(
        ci_loa_ba = ci_loa_ba,
        ci_loa_ba_mod = ci_loa_ba_mod,
        ci_loa_mover = ci_loa_mover,
        ci_loa_mover_mod = ci_loa_mover_mod,
        ci_loa_bt = ci_loa_bt,
        ci_loa_bt_mod = ci_loa_bt_mod
      )
    } else {
      list(
        ci_loa_ba = ci_loa_ba,
        ci_loa_ba_mod = ci_loa_ba_mod,
        ci_loa_mover = ci_loa_mover,
        ci_loa_mover_mod = ci_loa_mover_mod
      )
    }
  )
}
